version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders_db
    ports:
      - "5432:5432"
    networks:
      - backend

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - backend

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - backend

  order-service:
    build:
      context: ./OrderService
    ports:
      - "8081:8080"
    depends_on:
      - kafka
      - postgres
    networks:
      - backend

  inventory-service:
    build:
      context: ./InventoryService
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    networks:
      - backend

  notification-service:
    build:
      context: ./NotificationService
    ports:
      - "8083:8080"
    depends_on:
      - kafka
      - postgres
    networks:
      - backend

networks:
  backend:
    driver: bridge
