version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: online_store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    depends_on:
      - postgres
    ports:
      - "8081:8081"   # REST API порт
      - "9090:9091"   # gRPC порт (внешний 9090 → внутренний 9091)
    command: [ "sh", "-c", "sleep 20 && java -jar /app/app.jar" ]

  order-service:
      build: ./order-service
      container_name: order-service
      depends_on:
        - postgres
        - kafka
        - inventory-service
      ports:
        - "8080:8080"

  notification-service:
      build: ./notification-service
      container_name: notification-service
      depends_on:
        - postgres
        - kafka
      ports:
        - "8082:8080"

volumes:
  postgres_data: