server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/online_store
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

grpc:
  client:
    inventory-service:
      address: static://localhost:9091
      negotiation-type: plaintext

jwt:
  secret: your-super-secret-key-that-is-at-least-32-characters-long
  expiration: 3600000

app:
  kafka:
    topics:
      orders: "orders"

logging:
  level:
    com.example: DEBUG
    org.springframework.kafka: DEBUG