spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/onlineStoreOrderProcessingSystem
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
