server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/online_store
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

grpc:
  client:
    inventory-service:
      address: static://inventory-service:9091
      negotiation-type: plaintext

app:
  kafka:
    topic: orders

logging:
  level:
    com.example: DEBUG