server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/order_service_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# gRPC client configuration
grpc:
  client:
    inventory-service:
      address: static://inventory-service:9090
      negotiation-type: plaintext

# JWT Secret
jwt:
  secret: your-super-secret-key-that-is-at-least-32-characters-long
  expiration: 3600000

# Swagger configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

    app:
      kafka:
        topics:
          orders: "orders"