server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/online_store
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

    spring:
      kafka:
        bootstrap-servers: kafka:9092
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        properties:
          spring.json.trusted.packages: "*"

grpc:
  client:
    inventory-service:
      address: static://inventory-service:9091
      negotiation-type: plaintext
      enable-keep-alive: true
      keep-alive-without-calls: true

jwt:
  secret: "bmV3LXN1cGVyLXNlY3VyZS1zZWNyZXQta2V5LWZvci1qd3QtdG9rZW5zLTIwMjQ="
  expiration: 3600000

app:
  kafka:
    topics:
      orders: "orders"

logging:
  level:
    com.example: DEBUG
    org.springframework.kafka: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      enabled: true