version: '3.8'

services:
  inventory-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
      - "9090:9090"
    networks:
      - backend

networks:
  backend:
