version: '3.8'

services:
  order-db:
    image: postgres:17
    container_name: order-db
    restart: always
    environment:
      POSTGRES_DB: onlineStoreOrderProcessingSystem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5434:5432"
    volumes:
      - order_data:/var/lib/postgresql/data
    networks:
      - backend

  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-service
    depends_on:
      - order-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5434/onlineStoreOrderProcessingSystem
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:

volumes:
  order_data:
