server:
  port: 8081

grpc:
  server:
    port: 9091

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/online_store
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true
      connection-timeout: 30000
      maximum-pool-size: 5
      minimum-idle: 1
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level:
    com.example.InventoryService: DEBUG
    org.hibernate: DEBUG
    org.springframework.jdbc: DEBUG
    com.zaxxer.hikari: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      enabled: true